name: Update Project Pages

on:
  workflow_dispatch:

jobs:
  update-pages:
    runs-on: ubuntu-latest
    env:
      # List of project; Format: owner/repo:path/to/homepage
      PROJECTS: |
        obsidian7673/odin-recipes:.
        obsidian7673/odin-landing-page:.
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Setup Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch and copy each project
        run: |
          IFS=$'\n'
          for entry in $PROJECTS; do
            REPO="${entry%%:*}"
            OUTPUT="${entry##*:}"
            NAME=$(basename "$REPO")
            echo "Processing $REPO ($OUTPUT) -> $NAME"
            rm -rf "$NAME"
            echo "::group::Cloning $REPO"
            git -c credential.helper= clone --depth 1 "https://github.com/${REPO}.git" "temp-$NAME" || echo "Failed to clone $REPO"
            echo "::endgroup::"
            mkdir "$NAME"
            cp -r "temp-$NAME/$OUTPUT"/. "./$NAME/"
            rm -rf "./$NAME/.git" "./$NAME/.github" "temp-$NAME"
          done

      - name: Commit and push changes
        run: |
          git add .
          git diff --cached --quiet || git commit -m "Update project subfolders [auto]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/obsidian7673/project-pages.git
          git push
